events api 구현
ddip-team/ddip-be pull request #14
Opened 2023-11-06 11:51 UTC by seonghoo1217

> Closes #11 

## 상세 내용
- event api 구현
  - `events/me` 호출 시 자신의 Event 중 현재 진행중인 Event를 List형태로 묶어서 반환
  - 이벤트 생성시 유효하지 못한 날짜 값의 경우 예외 처리
  - UUID 및 ID를 DB에서 찾을 수 없을 경우 예외 처리 

## 비고
- 현재 모든 API에 대하여 success 처리를 하였습니다. 이부분에 대해 개선점을 찾아야할 것같은데 확인해주시기 바랍니다.
- 현재 회원 정보를 `MemberRepository`에서 직접적으로 호출하여 사용중에 있습니다. Merge 후 변경하고자합니다.
- Event Response 양식이 공통되는 부분이 맣아 `EventCommonReponse`를 만들어 Client에게 전달하는데 좋은 방법일까요?

2023-11-06 13:58 UTC, Gongmeda requested changes

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public EventCommonResDTO createNovelEvent(EventCreateReqDTO eventCreateDTO,Long memberId) {
application 레이어에서 presentaion 레이어의 DTO에 의존하면 안될 것 같습니다.

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public EventCommonResDTO createNovelEvent(EventCreateReqDTO eventCreateDTO,Long memberId) {
메소드명의 Novel이 무슨 뜻인가요?

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/exception/NotFoundIdException.java
> +public class NotFoundIdException extends RuntimeException{
도메인에 종속적인 Exception명 사용하는게 낫지 않을까요? Member에서는 그렇게 처리했어요.
만약 그렇게 바꾼다면 NotFoundIdException보다는 EventNotFoundException이 나을 것 같습니다.

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/exception/NotFoundUuidException.java
> +public class NotFoundUuidException extends RuntimeException{
id로 조회한 경우랑 uuid로 조회한 경우의 예외를 분리해야 하는 이유가 뭔가요?

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern = "yyyy-MM-dd'T'HH:mm:ss",timezone = "Asia/Seoul")
Event 객체를 직접 presentation 레이어에서 역직렬화 할 경우가 없을 것 같은데 `@JsonFormat`을 사용한 이유가 뭔가요?

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/repository/EventRepository.java
> +    Optional<List<Event>> findByMember(Member member);
반환값이 List 타입인데 Optional을 사용하신 이유가 뭔가요?

2023-11-06 13:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/presentation/EventAPI.java
> +        return new ResponseEnvelope<>("success",novelEvent,null);
성공시 code를 null로 처리하는거 아니었나요?

2023-11-06 13:58 UTC, Gongmeda commented
저희 클래스 네이밍 컨벤션을 안정했었네요. 정합시다.

2023-11-06 14:16 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public EventCommonResDTO createNovelEvent(EventCreateReqDTO eventCreateDTO,Long memberId) {
필드값이 많아서 저렇게 처리했는데 의존성 측면을 더 고려하는것이 맞을까요?

2023-11-06 14:16 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public EventCommonResDTO createNovelEvent(EventCreateReqDTO eventCreateDTO,Long memberId) {
새로운 이벤트 생성한다는 의미로 작성했습니다

2023-11-06 14:17 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/application/exception/NotFoundIdException.java
> +public class NotFoundIdException extends RuntimeException{
넵 좋은의견인 것 같습니다

2023-11-06 14:19 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/application/exception/NotFoundUuidException.java
> +public class NotFoundUuidException extends RuntimeException{
필드값에 따라 예외를 다르게 처리하는게 좋을 것같다고 생각했습니다.

UUID는 core한 값인만큼 예외를 따로두는게 좋다고 생각하기도 했구요

2023-11-06 14:21 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/presentation/EventAPI.java
> +        return new ResponseEnvelope<>("success",novelEvent,null);
이전에 작성한 코드라 수정하겠습니다

2023-11-06 14:22 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/repository/EventRepository.java
> +    Optional<List<Event>> findByMember(Member member);
Optional하게 두어서 예외 처리할걸 고려했었는데 현 시점에서는 필요없는거 같긴해요. 삭제하는게 좋을까요?

2023-11-06 14:22 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern = "yyyy-MM-dd'T'HH:mm:ss",timezone = "Asia/Seoul")
DTO를 통해서 역직렬화 작업을 대비해서 사용했습니다. 지양하는게 좋을까요?

2023-11-06 14:58 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public EventCommonResDTO createNovelEvent(EventCreateReqDTO eventCreateDTO,Long memberId) {
불필요한 필드가 많은건 별도의 DTO를 활용하는게 맞긴 하지만 Response DTO와는 다른 application 레이어에 종속된 DTO여야 할 것 같습니다.
정리하자면 Event -> EventDto -> EventCommonResDTO 이런 흐름이어야 할 것 같네요.

다만, 이건 쿼리부터 필요한 필드만 select 해오는 처리를 했을 때나 필요한 부분인 것 같아서 일단은 Event 엔티티로 내리면 될 것 같습니다.

2023-11-06 14:59 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public EventCommonResDTO createNovelEvent(EventCreateReqDTO eventCreateDTO,Long memberId) {
불필요한 키워드 같습니다. createEvent만 해도 "이벤트를 생성한다" 인데, 이미 존재하는 이벤트를 생성한다는 의미는 말이 안되니까요.

2023-11-06 15:05 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/exception/NotFoundUuidException.java
> +public class NotFoundUuidException extends RuntimeException{
그렇게 보면 모든 필드에 대한 조회마다 예외를 별도로 처리해야 할 것 같은데요.

분리는 결국 '분리해서 오는 이점이 무엇인가'가 기준인데 지금 상황에서 분리하는 것과 안하는 것의 차이가 없기 때문에 적절하지 않다고 생각해요.
추후에 분리된 예외에 따라 분기점이 생기는 케이스를 구체적으로 고려하고 계신게 아니라면 불필요한 처리같습니다.

2023-11-06 15:06 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern = "yyyy-MM-dd'T'HH:mm:ss",timezone = "Asia/Seoul")
@JsonFormat이 Entity -> DTO 로 매핑할 때 전이가 되나요?

2023-11-06 15:07 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/repository/EventRepository.java
> +    Optional<List<Event>> findByMember(Member member);
예외 처리할게 없습니다. 해당 메소드에서 List 자체가 null로 반환될 일은 없으니까요.

2023-11-06 18:23 UTC, Gongmeda requested changes

2023-11-06 18:23 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +    public List<EventCommonResDTO> findOwnEvent(Long memberId) {
진행중인 이벤트만 가져오면 안돼요. 옵셔널하게 필터링할 수 있도록 해야 합니다.

2023-11-06 18:23 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> +        return ownEvents.stream()
모든 이벤트를 가져와서 애플리케이션애서 핉터링하는게 아니라 WHERE문 쿼리로 필터링되게 처리해주세요.

2023-11-06 18:23 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/repository/EventRepository.java
> +    List<Event> findByMember(Member member);
저는 주로 return type이 List면 `findByMember` 가 아니라 `findAllByMember` 로 사용하긴합니다.
이렇게 해도 동작은 하는데 단일 값 반환이랑 구분이 잘 안되긴해요.

2023-11-07 03:27 UTC, Gongmeda approved these changes

2023-11-07 05:40 UTC, merged