events v2 api 구현
ddip-team/ddip-be pull request #29
Opened 2023-11-13 11:45 UTC by seonghoo1217

> Closes #25

## 상세 내용
- Events 와 SuccessRecord에 대한 필드 값을 추가
  - 공통 : 이벤트 참여자 폼 필드
  - `Event` : 이벤트 이미지, 이벤트 성공 이미지
  - `SuccessRecord` : 타임스탬프 필드
- 이벤트 참여자 폼 작성, 조회 API 작성
- 이벤트 성공 참여자 목록 리스트 조회
- 기존 이벤트 API 수정
- Json 타입 DB 저장을 위한 컨버터 작성
## 비고
- JsonConverter 데이터 read시 처리에 대해 더 좋은 의견이 있다면 부탁드립니다

2023-11-13 15:41 UTC, Gongmeda requested changes

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> -    public Event createEvent(String title, Integer permitCount, String content, ZonedDateTime start, ZonedDateTime end, Long memberId) {
이 부분은 제가 맡은 부분 아닌가요..?

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @Nullable
이거 왜 붙이신건가요?

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    private Map<String, String> jsonString;
필드명에 json이 들어갈 필요가 있을까요? `successForm` 같이 용도를 명확하게 나타내는게 나을꺼같아요

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/SuccessRecord.java
> +    private Map<String, String> jsonString;
`Event`의 필드와 마찬가지입니다. 다만 네이밍은 정확히 동일한 용도가 아니니 다르게 해야할 것 같네요.
지금 생각나는 이름은 `formInputValue` 정도인데 좀 애매하네요

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/SuccessRecord.java
> +    private ZonedDateTime timeStamp;
`timestamp` 로 바꿔주세요

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/SuccessRecord.java
> +    public void createJsonString(Map<String, String> jsonString){
메소드명이 명확하지 않아요. 새로운걸 생성하는게 아닌데 create는 문맥이 좀 달라지는 단어인것 같아요.
`update` 또는 `set` 이 나을 것 같고, 필드명을 바꾸신다면 함께 바꿔주세요.

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/repository/PermitRepository.java
> +    List<SuccessRecord> findByEventUuidOrderByTimeStampAsc(UUID uuid, Pageable pageable);
orderBy는 네이밍에 함께 넣지 않고 `pageable` 에 넘기는 값으로 조정이 가능하므로 범용성을 생각한다면 메소드명에 넣을 필요는 없을 것 같습니다

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/global/util/JsonConverter.java
> +    public Map<String, String> convertToEntityAttribute(String successFormat) {
null 체킹 안해도 문제 안생기나요?

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/presentation/dto/request/CreateEventReq.java
>  public class CreateEventReq {
이 DTO 수정도 제가 맡은 부분이라 머지하면 겹칠 것 같아요

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/presentation/dto/request/CreateJsonStringReq.java
> +public class CreateJsonStringReq {
위에서 얘기한 네이밍 이슈와 함께 봐주세요

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/presentation/dto/response/EventSuccessRes.java
> +public class EventSuccessRes {
Getter가 없는데 deserialization에 문제가 안생기나요?

2023-11-13 15:41 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/presentation/dto/response/EventSuccessRes.java
> +    private String successContent;
final 처리가 안되어있는 이유가 있나요?

2023-11-13 18:29 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> -    public Event createEvent(String title, Integer permitCount, String content, ZonedDateTime start, ZonedDateTime end, Long memberId) {
imgUrl과 successImgUrl 필드 추가하면서 함께 처리해버린 것 같습니다 죄송합니다

2023-11-13 18:30 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @Nullable
`@Nullable` 말씀하신건가요?

2023-11-13 18:31 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    private Map<String, String> jsonString;
이해했습니다. 그럼 반대로 JsonConverter 클래스의 네이밍은 어떻게 생각하시나요

2023-11-13 18:31 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/SuccessRecord.java
> +    private Map<String, String> jsonString;
네 적절한 이름 고안 후 변경하겠습니다

2023-11-13 18:31 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/SuccessRecord.java
> +    private ZonedDateTime timeStamp;
네 알겠습니다.

2023-11-13 18:32 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/SuccessRecord.java
> +    public void createJsonString(Map<String, String> jsonString){
네 확인했습니다

2023-11-13 18:32 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/repository/PermitRepository.java
> +    List<SuccessRecord> findByEventUuidOrderByTimeStampAsc(UUID uuid, Pageable pageable);
그렇다면 페이징처리와 함께 sort 처리하면 될까요?

2023-11-13 18:33 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/global/util/JsonConverter.java
> +    public Map<String, String> convertToEntityAttribute(String successFormat) {
DB 저장시 문제가 되지 않았었습니다. 혹시 제가 놓친 부분이 있을까요?

2023-11-13 18:36 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/presentation/dto/response/EventSuccessRes.java
> +    private String successContent;
이전에 말씀드린 DTO 필드 값을 final로 처리한다면 record 타입이 적절하지 않을까? 싶어서 여쭤본 부분이었습니다.
그래서 일반 클래스 타입이라면 final 처리를 하지 않고 추후 리팩터링 단계를 생각하였습니다

2023-11-13 18:40 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/application/EventService.java
> -    public Event createEvent(String title, Integer permitCount, String content, ZonedDateTime start, ZonedDateTime end, Long memberId) {
수정하였니다

2023-11-13 19:09 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/presentation/dto/response/EventSuccessRes.java
> +    private String successContent;
현재 final 처리하였고 추후 successImageUrl 고려하여, 현재 제 Event 엔티티에선 필드값을 제거하였고 #27 브랜치 기준으로 작성된 필드값 들어올수 있도록 변경하였습니다.

2023-11-14 04:47 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @Nullable
넵

2023-11-14 04:48 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    private Map<String, String> jsonString;
converter는 그대로가도 될꺼같아요

2023-11-14 04:48 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/repository/PermitRepository.java
> +    List<SuccessRecord> findByEventUuidOrderByTimeStampAsc(UUID uuid, Pageable pageable);
넵

2023-11-14 04:49 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/global/util/JsonConverter.java
> +    public Map<String, String> convertToEntityAttribute(String successFormat) {
저번에 null값 조회시에 문제 생긴다고 하셨던거같은데 수정이 안되어서요

2023-11-14 04:51 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/presentation/dto/response/EventSuccessRes.java
> +    private String successContent;
제 기억에는 일단 클래스로 처리하고 일괄 record 타입으로 리팩토링한다고 말씀드렸돈것같습니다. final 처리 되어있는 클래스여야 record로 바꿨을 때 큰 차이가 없는 상태인거라 붙였던겁니다

2023-11-14 06:02 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/global/util/JsonConverter.java
> +    public Map<String, String> convertToEntityAttribute(String successFormat) {
API 조회 단계에서 NPE가 발생하였었는데 현재 @Nullable 어노테이션 사용이후로  발생하지 않는 것같습니다

2023-11-14 06:02 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/repository/PermitRepository.java
> +    List<SuccessRecord> findByEventUuidOrderByTimeStampAsc(UUID uuid, Pageable pageable);
변경했습니다

2023-11-14 06:03 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/Event.java
> +    @Nullable
event 엔티티가 가지고 있는 값들 중 빈값을 가져도 되는 필드였기에 명시적으로 처리하기위해 사용했습니다

2023-11-15 09:49 UTC, Gongmeda approved these changes

2023-11-15 09:49 UTC, merged