Entity Not Null, Unique 인덱스 처리
ddip-team/ddip-be pull request #45
Opened 2023-12-02 10:50 UTC by seonghoo1217

> Closes #43

## 상세 내용
- 각 Entity 별로 필요에 따라 컬럼에 Not Null과 Unique를 추가
- 또한, 인덱싱 고려사항을 문서화하여 성능 수치를 비교
## 비고
- Wiki에 작성되기 적절한 내용인지 판단이 필요합니다.
- 또한 놓친 처리부분이 있다면 의견 부탁드립니다

2023-12-03 16:28 UTC, Gongmeda requested changes

2023-12-03 16:28 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/EventDuration.java
> +    @Column(nullable = false, name = "start_date_time")
여기만 칼럼명을 명시적으로 추가한 이유가 뭔가요?

2023-12-05 04:29 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/EventDuration.java
> +    @Column(nullable = false, name = "start_date_time")
Index 조합시 startDateTime 필드를 인식하지 못하는 기대값(start_date_time)으로 인식하지 못하기에 명시하여주었습니다.

2023-12-05 08:26 UTC, Gongmeda commented on src/main/java/ddip/me/ddipbe/domain/EventDuration.java
> +    @Column(nullable = false, name = "start_date_time")
해당 칼럼으로 생성한 인덱스가 없는데요?

2023-12-05 08:57 UTC, seonghoo1217 commented on src/main/java/ddip/me/ddipbe/domain/EventDuration.java
> +    @Column(nullable = false, name = "start_date_time")
이전에 여러 인덱스 케이스를 테스트하다 보니 지우는 걸 까먹었습니다. 제거 후 커밋하겠습니다

2023-12-05 09:13 UTC, Gongmeda approved these changes

2023-12-05 11:21 UTC, merged