모니터링 시스템 구축
ddip-team/ddip-be pull request #49
Opened 2023-12-14 20:31 UTC by Gongmeda

> Closes #47

## 상세 내용

- 모니터링 시스템 구축
  - Prometheus로 메트릭 수집
  - Grafana로 대시보드 생성
  - 추가 설정 없이 자동 연결되도록 처리
  - Thanos로 2시간마다 AWS S3로 메트릭 업로드 처리하여 메모리 부족 문제 완화

## 비고

2023-12-15 07:33 UTC, seonghoo1217 requested changes

2023-12-15 07:33 UTC, seonghoo1217 commented on infra/alb.tf
> +resource "aws_lb_listener_rule" "block-actuator-path" {
이건 어떤 처리의 일부인가요?

2023-12-15 07:33 UTC, seonghoo1217 commented on docker/monitor/prometheus/config/rule.yml
> +          summary: "Instance {{ $labels.instance }} down"
해당 yml파일은 무슨 역할을 수행하나요?

2023-12-15 07:38 UTC, Gongmeda commented on infra/alb.tf
> +resource "aws_lb_listener_rule" "block-actuator-path" {
spring actuactor에서 `/actuator` 라는 경로로 metric들을 공개하는데, 이걸 외부에서 볼 수 없도록 로드밸런서 룰로 막은거에요

2023-12-15 07:41 UTC, Gongmeda commented on docker/monitor/prometheus/config/rule.yml
> +          summary: "Instance {{ $labels.instance }} down"
원래 prometheus에서도 metric에 따라 알림을 설정할 수 있는데, 그걸 설정할 수 있는 파일입니다. 저는 알림을 grafana쪽에서 처리할꺼라 현재는 제거한 파일입니다.

2023-12-16 05:17 UTC, seonghoo1217 approved these changes

2023-12-16 06:28 UTC, merged